### ISSUE TITLE
Valinor should have an option to specify debugger

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/valinor#10]
Since different targets have different debug interfaces, you can't just assume everyone uses CMSIS-DAP. It's a major hassle to have to reconfigure the debug adapter every single time upon executing yotta debug.

If Valinor gets an extra flag to specify the debug adapter type, it could be passed by the yotta target definition (target.json) as part of the debug command, and save everyone from another headache.

**Comment by autopulated** [comment]
Out of interest, which other debugger are you using?

**Comment by stevew817** [comment]
JLink...

**Comment by 0xc0170** [comment]
It should be possible, as pgen does support jlink for uvision for example. I might find a moment to add this.

**Comment by autopulated** [comment]
For gdb+jlink support it'll require a little more work in valinor, as it'll need to run jlinkgdbserver, but still should be fairly straightforward.

**Comment by stevew817** [comment]
gdb+jlink is already supported through yotta (defining debug-server in target.json)...

Would really appreciate it also happening for uvision.

**Comment by autopulated** [comment]
Yes, but note that debugServer in target.json is deprecated – in the future the scripts.debug property will need to be a program (like valinor) that both runs the debug server and starts the debugger.

We've chosen that design because people often want to use different debuggers with the same target, and having a program like valinor that can choose between the debugger, and deal with all the host-platform-specific peculiarities enables that.

**Comment by 0xc0170** [comment]
@stevew817 I am just pushing new changes to definitions and project generator, which will support debugger options for targets. I assume this can be effective once #18 is pushed. I already specified jlink for all silabs targets, please verify if everything works and its defined properly.

If a target is passed to valinor (lets say frdm-k64f), it will be searched for debugger specification in the definitions. If MCU is specified, debugger is not searched for. 

For instance:
valinor executable --tar frdm-k64f (target, contain additional data like a debugger)
valinor executable --tar mk64fn1m0xxx12 (MCU,only required mcu definition for a tool)

This of course can be expanded in the future, there are targets which have more debugger options (frdm-k64f for instance).

**Comment by 0xc0170** [comment]
@autopulated this could provide us some help to decide which gdb to use? If a target has cmsis-dap , use pyOCD by default. If j-link, use jlink gdb? I will create a new issue for this feature request

**Comment by autopulated** [comment]
Yeah reading that information from the progen target description would definitely be useful.

**Comment by 0xc0170** [comment]
@stevew817 I am closing this one as debuggers are now supported, as described above..
