### ISSUE TITLE
Valinor depends on wrong version of project-generator

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/valinor#6]
Valinor's dependencies are ```>= 0.5.7 && <1.0``` but project-generator 6.0 introduces breaking changes, so valinor should depend on ```>= 0.5.6 && <0.6.0```.

**Comment by 0xc0170** [comment]
I noticed this and fixed it in #4. However, It's on hold currently, waiting for 0.7 to be released.

We can fix this immediately with patched version. I'll send PR
